### ISSUE TITLE
"No such file " log in sapp

### ISSUE THREAD

**Issue by DavidZhang-7** [facebook/mariana-trench#132]
# Bug
**Bug description**
Please enter a clear and concise description of what the bug is.

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
```
Output goes here
```

**Additional context**

**Comment by DavidZhang-7** [comment]
You can download app and source directory zip that I used by the links. 
https://drive.google.com/u/0/uc?id=1C-wgbarPqVeoedvP2E3fgZiEvvyykYSf&export=download
https://drive.google.com/u/0/uc?id=10CjxqNBaZHMA1U2rINb2tfkkqpTjaSi0&export=download

**Comment by arthaud** [comment]
cc @dkgi since you implemented that UI

**Comment by felipecaon** [comment]
Same issue
