### ISSUE TITLE
Request for Features Description 

### ISSUE THREAD

**Issue by DavidZhang-7** [facebook/mariana-trench#133]
In configuration json files, it is requested to add features into source/sink sometimes. But I dont know the meaning of all features. Could u provide features description?

**Comment by DavidZhang-7** [comment]
Could u explain features as follows? I dont konw when to use them.
always-via-caller-unexported
via-intent-data
via-explicit-intent
cast:uri
always-via-explicit-intent
always-via-caller-exported
always-via-caller-permission
always-cast:uri
always-via-inner-class-this

**Comment by arthaud** [comment]
Thanks for reaching out.
This is now documented here: https://mariana-tren.ch/docs/feature-descriptions/
I will close this issue for now, please re-open if you have further questions.

**Comment by DavidZhang-7** [comment]
Really helpful! Thanks!
