### ISSUE TITLE
Error to complie JsonReaderWriter.cpp by build_static_binary.py

### ISSUE THREAD

**Issue by Securee** [facebook/mariana-trench#155]
# Bug
**Bug description**
I want build static binary by "python3 build_static_binary.py",but when to complie the new add JsonReaderWriter.cpp,there are some error:

**Reproduction steps**
1 clone the source code
2 cd script
3 python3 build_static_binary.py

**Expected behavior**
It should complile succ for the static binary

**Logs**
[ 30%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/FulfilledPartialKindState.cpp.o
[ 30%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/Highlights.cpp.o
[ 31%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/IntentRoutingAnalyzer.cpp.o
[ 32%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/Interprocedural.cpp.o
[ 32%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/Issue.cpp.o
[ 34%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/JsonReaderWriter.cpp.o
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp: In static member function ‘static Json::Value marianatrench::JsonReader::parse_json_file(const std::filesystem::__cxx11::path&)’:
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:34:17: error: aggregate ‘std::ifstream file’ has incomplete type and cannot be defined
   34 |   std::ifstream file;
      |                 ^~~~
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:35:34: error: incomplete type ‘std::ifstream’ {aka ‘std::basic_ifstream<char>’} used in nested name specifier
   35 |   file.exceptions(std::ifstream::failbit | std::ifstream::badbit);
      |                                  ^~~~~~~
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:35:59: error: incomplete type ‘std::ifstream’ {aka ‘std::basic_ifstream<char>’} used in nested name specifier
   35 |   file.exceptions(std::ifstream::failbit | std::ifstream::badbit);
      |                                                           ^~~~~~
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:38:40: error: expected unqualified-id before ‘&’ token
   38 |   } catch (const std::ifstream::failure&) {
      |                                        ^
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:38:40: error: expected ‘)’ before ‘&’ token
   38 |   } catch (const std::ifstream::failure&) {
      |           ~                            ^
      |                                        )
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:38:40: error: expected ‘{’ before ‘&’ token
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:38:41: error: expected primary-expression before ‘)’ token
   38 |   } catch (const std::ifstream::failure&) {
      |                                         ^
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp: In static member function ‘static void marianatrench::JsonWriter::write_json_file(const std::filesystem::__cxx11::path&, const Json::Value&)’:
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:87:17: error: aggregate ‘std::ofstream file’ has incomplete type and cannot be defined
   87 |   std::ofstream file;
      |                 ^~~~
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:88:34: error: incomplete type ‘std::ofstream’ {aka ‘std::basic_ofstream<char>’} used in nested name specifier
   88 |   file.exceptions(std::ofstream::failbit | std::ofstream::badbit);
      |                                  ^~~~~~~
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:88:59: error: incomplete type ‘std::ofstream’ {aka ‘std::basic_ofstream<char>’} used in nested name specifier
   88 |   file.exceptions(std::ofstream::failbit | std::ofstream::badbit);
      |                                                           ^~~~~~
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp: In lambda function:
/home/lzy/tools/mariana-trench/source/JsonReaderWriter.cpp:120:23: error: aggregate ‘std::ofstream batch_stream’ has incomplete type and cannot be defined
  120 |         std::ofstream batch_stream;
      |                       ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/mariana-trench-library.dir/build.make:678: CMakeFiles/mariana-trench-library.dir/source/JsonReaderWriter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:91: CMakeFiles/mariana-trench-library.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/home/lzy/tools/mariana-trench/scripts/build_static_binary.py", line 434, in <module>
    main()
  File "/home/lzy/tools/mariana-trench/scripts/build_static_binary.py", line 417, in main
    mariana_trench = _build_mariana_trench(
  File "/home/lzy/tools/mariana-trench/scripts/build_static_binary.py", line 388, in _build_mariana_trench
    _run(["make", f"-j{arguments.jobs}"], cwd=build_directory)
  File "/home/lzy/tools/mariana-trench/scripts/build_static_binary.py", line 60, in _run
    return subprocess.run(command, check=True, text=True, cwd=cwd, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2.

Output goes here
```

**Additional context**
Add any other context about the problem here.

**Comment by arthaud** [comment]
Hi @Securee, thanks for reaching out.

Does adding `#include <fstream>` on top of `source/JsonReaderWriter.cpp` fix the issue?

**Comment by Securee** [comment]
> Hi @Securee, thanks for reaching out.
> 
> Does adding `#include <fstream>` on top of `source/JsonReaderWriter.cpp` fix the issue?

yes,it does fix the issue. thank you.
