### ISSUE TITLE
Inconsistent behaviour with unreachable code

### ISSUE THREAD

**Issue by draftyfrog** [facebook/mariana-trench#169]
# Bug
**Bug description**
Consider the following code:
```java
 boolean selector = false;
 String taint = source();

 if (selector) {
     sink1(taint);
 }

 if (false) {
     sink2(taint);
 }
```
where the return value of `source()` is specified as a source and `sink1()`and `sink2()` are both defined as sinks. As can be seen in the code, both sinks are unreachable, but mariana-trench returns `sink1()` as found issue (but doesn't return `sink2()`).

**Comment by arthaud** [comment]
Hi @draftyfrog,

My guess is that the compiler probably removed the `if (false)` branch entirely. Mariana Trench analyzes the APK directly, after the compiler ran, so we cannot see things that have been removed by the compiler.

**Comment by draftyfrog** [comment]
Hi @arthaud, thanks for getting back! You're right, I reverse-engineered my apk and the compiler removed the second if-branch. My mistake - thank you!
