### ISSUE TITLE
Cannot build on Ubuntu: re2 CMake module is required, but it is neither a part of CMake stdlib, nor of re2c package 

### ISSUE THREAD

**Issue by KOLANICH** [facebook/mariana-trench#41]

**Comment by arthaud** [comment]
Hi, thanks for trying mariana-trench.

Could you provide us with more information about the failure you are encountering?
Which platform are you using? - We only support Linux and macOS
What command(s) did you run and what is the output? Please provide us with the full logs.

It looks like you are trying to build Mariana Trench from source. Have you tried to install it with `pip` instead?

**Comment by KOLANICH** [comment]
>It looks like you are trying to build Mariana Trench from source.

It not only looks like, in the title it is explicitly written

>Cannot **build**

>Have you tried to install it with pip instead?

No. The project doesn't seem (at least the repo was cloned fast enough, I may be wrong, I haven't really tried actual compilation, since building has stopped on CMake invokation phase) to be too heavy in order not to try to build it myself. Also I don't trust pypi much and prefer to stay away of it.

>Which platform are you using? - We only support Linux and macOS

In the title it is written:

>Cannot build on **Ubuntu**

More precisely, it is Ubuntu 21.10 `impish`. `x86_64` CPU arch (but on other PCs I still use i686 and even i586, so they should be supported too).

Since you require CMake that is not available in this distro, I have downloaded the latest CMake from the official website and used it for trying to build this project.

>What command(s) did you run and what is the output? Please provide us with the full logs.

I cannot provide them right now, but as I have said, the issue is that there is no CMake module for re2.

P.S. I have just noticed, that `re2` is a `re2` library by Google, not `re2c` parser generator. While I had already had it installed, the package in the distro doesn't have the module for CMake. Probably I should create a bug about it.

I close this bug for now. Would try to fix that and try building again, if I have the same error, I'd reopen, if I can.

**Comment by arthaud** [comment]
Please follow https://www.internalfb.com/intern/staticdocs/mariana-trench/docs/developers-guide/ if you want to build Mariana Trench from source. Dependencies can be easily installed with linuxbrew.

**Comment by catfly1** [comment]
> Please follow https://mariana-tren.ch/docs/developers-guide if you want to build Mariana Trench from source. Dependencies can be easily installed with linuxbrew.

This site returns 404, FYI. FWIW I had to build RE2 from source then drop https://github.com/grpc/grpc/raw/52299822737ef4d4418296695dc061575f10f5f3/cmake/modules/Findre2.cmake into mariana-trench cmake dir

**Comment by arthaud** [comment]
https://mariana-tren.ch/docs/contribution is the right link.
