### ISSUE TITLE
Facing issues in installing marian-trench package using pip.

### ISSUE THREAD

**Issue by Gojo1729** [facebook/mariana-trench#46]
Hi,
I'm trying to install the python package using pip and I'm getting the following error ->

`ERROR: Could not build wheels for mariana-trench which use PEP 517 and cannot be installed directly` . 

Here are the following details -> 
1. OS - Windows 10 Home 
2. Python - 3.8.8 
3. Pip - 21.2.4

**Comment by arthaud** [comment]
Hi @Gojo1729, thanks for reaching out.
Unfortunately, we do not support Windows.
I would recommend to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) and install Ubuntu with it, then try pip install again.

**Comment by Gojo1729** [comment]
Thanks for the update @arthaud
