### ISSUE TITLE
Bad dex magic dex

### ISSUE THREAD

**Issue by downright-ux** [facebook/mariana-trench#58]
Hi,
I'm getting the following issue when running with APK's
```
INFO Initializing Redex...
error: /tmp/mt-static-cnhs17k0/build/redex-master/libredex/DexLoader.cpp:49: void validate_dex_header(const dex_header*, size_t, int): assertion `supported' failed.
Bad dex magic dex
039 for support_dex_version 37
```
Any help here would be great.

Thanks

**Comment by Securee** [comment]
I resolved this issued by:
1、set up the development environment
2、before re-compiled the redex, add dex version 39 support in the redex\libredex\DexLoader.cpp
static void validate_dex_header(const dex_header* dh,
                                size_t dexsize,
                                int support_dex_version) {
  bool supported = false;
  switch (support_dex_version) {
**case 39:
    supported = supported ||
                !memcmp(dh->magic, DEX_HEADER_DEXMAGIC_V39, sizeof(dh->magic));**
  case 38:
    supported = supported ||
                !memcmp(dh->magic, DEX_HEADER_DEXMAGIC_V38, sizeof(dh->magic));

3、modify the default support dex version to 39 in the source/MarianaTrench.cpp
     void MarianaTrench::run(const program_options::variables_map& variables) {
     ...
     context.stores = init(
      boost::join(system_jar_paths, ","),
      options.apk_directory(),
      options.dex_directory(),
      /* balloon */ true,
      /* support_dex_version */ 39);
4、build the mariana-trench

**Comment by arthaud** [comment]
Redex might not support version 39. Please open an issue at https://github.com/facebook/redex

**Comment by downright-ux** [comment]
We were able to get that working, Thank you.

**Comment by firmianay** [comment]
I have the same problem, is there an update?
