### ISSUE TITLE
Sapp browser view is not working.

### ISSUE THREAD

**Issue by akshayprasad** [facebook/mariana-trench#65]
![Screenshot 2021-11-01 at 4 31 21 PM](https://user-images.githubusercontent.com/18460224/139697725-b8701001-d06e-421d-800f-069f3b059752.png)
<img width="1348" alt="Screenshot 2021-11-01 at 4 31 08 PM" src="https://user-images.githubusercontent.com/18460224/139697729-a290ced4-b700-4fed-9456-26ac06381b14.png">

As per the attached image, the browser view of sapp is not working for mariana-trench. Kindly help me with the same.

Looking forward to hearing from you.
Thanks in advance.

**Comment by akshayprasad** [comment]
Hello @arthaud ,

Thanks for the reply.
While it is running I executed the command and I could see the following results.

 akshayprasad@Akshays-MBP  ~  curl -v http://localhost:5000/
*   Trying ::1:5000...
* Connected to localhost (::1) port 5000 (#0)
> GET / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Length: 0
< Server: AirTunes/595.13.1
<
<img width="1000" alt="Screenshot 2021-11-01 at 9 22 58 PM" src="https://user-images.githubusercontent.com/18460224/139737059-9c2456fe-7d96-4c22-9739-1d422c4594f2.png">

* Connection #0 to host localhost left intact

**Comment by arthaud** [comment]
It looks like you have another server running that port, see:
`Server: AirTunes/595.13.1`

Please use a different port for sapp. There should be an option for it (see `sapp server --help`). If not, please open an issue at https://github.com/facebook/sapp

**Comment by akshayprasad** [comment]
Thanks for the reply @arthaud .

Can I change the port of sapp?

**Comment by arthaud** [comment]
Apparently, there is no option for it, but it should be easy to add.
Please open an issue at https://github.com/facebook/sapp
