### ISSUE TITLE
are there documents about the architecture of mariana?

### ISSUE THREAD

**Issue by nkbai** [facebook/mariana-trench#66]
Hello, I have gone through https://mariana-tren.ch/docs and read all the documents in the code, but I still want to know more about Mariana's design architecture and theory. Is there any other paper or presentation about that which may give more insights? Really appreciate that.

**Comment by arthaud** [comment]
Hi @nkbai,
You can look at https://pyre-check.org/docs/pysa-implementation-details - This is for pysa, our taint analyzer for python, but it uses the same algorithm under the hood.
