### ISSUE TITLE
Source from constant?

### ISSUE THREAD

**Issue by evilpan** [facebook/mariana-trench#79]
Hi, all,

I was trying to write custom rule scan for hardcoded crypto key like:

```java
new SecretKeySpec("some-key".getBytes(), "AES");
```

However I can't find any resources in the document about defining Source from constant (literal string, static fields, etc.), Is it possible to scan for such issues with MT anyway?

**Comment by arthaud** [comment]
Unfortunately, mariana trench does not currently support string literals as sources.
We might implement this later if this becomes a high priority for our internal use cases.
